In [23]:

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

dataset=pd.read_csv('sample_data/Data_for_Transformation.csv')
# print("data : ")
# print(dataset)

x=dataset.iloc[:,1:-1].values
# print("x : ");
# print(x)

y=dataset.iloc[:2,:-1].values
# print("y : ")
# print(y)


print("x for transformation : ")
print(x)


scaler=MinMaxScaler()
print()
print("x after transformation : ")
x_transformed=scaler.fit_transform(x)
print(x_transformed)

std=StandardScaler()
x_std=std.fit_transform(x)
print()
print("x_std : ")
print(x_std)

u=np.mean(x,axis=0)
std=np.std(x,axis=0)
print(u)
print(std)
print((x[0][0]-u[0])/std[0])

x for transformation :
[[   44 72000]
 [   27 48000]
 [   30 54000]
 [   38 61000]
 [   40 68000]
 [   35 58000]
 [   39 52000]
 [   48 79000]
 [   50 83000]
 [   37 67000]
 [   45 55000]]

x after transformation :
[[0.73913043 0.68571429]
 [0.         0.        ]
 [0.13043478 0.17142857]
 [0.47826087 0.37142857]
 [0.56521739 0.57142857]
 [0.34782609 0.28571429]
 [0.52173913 0.11428571]
 [0.91304348 0.88571429]
 [1.         1.        ]
 [0.43478261 0.54285714]
 [0.7826087  0.2       ]]

x_std :
[[ 0.68188156  0.79548755]
 [-1.81835082 -1.41513049]
 [-1.37713334 -0.86247598]
 [-0.2005534  -0.21771238]
 [ 0.09359159  0.42705121]
 [-0.64177088 -0.49403964]
 [-0.05348091 -1.04669415]
 [ 1.27017153  1.44025115]
 [ 1.56431652  1.80868749]
 [-0.34762589  0.33494213]
 [ 0.82895405 -0.77036689]]
[3.93636364e+01 6.33636364e+04]
[6.79936798e+00 1.08566923e+04]
0.6818815584676956

In [44]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

dataset=pd.read_csv('sample_data/Data_for_Categorical_Values.csv')
# print("dataset : ",dataset)
# print("dataset statistics : ",dataset.describe())

x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values
print("x : ",x)
# print("y : ",y)

le=LabelEncoder()
x[:,0]=le.fit_transform(x[:,0])
print(x)

country=dataset["Country"]
dummy=pd.get_dummies(country)
print("dummy : ",dummy)

new_dataset=dataset.drop(['Country','Purchased'],axis=1)
merged_dataset=pd.concat([dummy,new_dataset],axis=1)
print(merged_dataset)

onehotencoder=OneHotEncoder()

onehot_dataset=onehotencoder.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()
print(onehot_dataset)

dfonehot=pd.DataFrame(x,colums=["Country_"+for])

x :  [['France' 44 72000]
 ['Spain' 27 48000]
 ['Germany' 30 54000]
 ['Spain' 38 61000]
 ['Germany' 40 68000]
 ['France' 35 58000]
 ['Spain' 39 52000]
 ['France' 48 79000]
 ['Germany' 50 83000]
 ['France' 37 67000]
 ['Spain' 45 55000]]
[[0 44 72000]
 [2 27 48000]
 [1 30 54000]
 [2 38 61000]
 [1 40 68000]
 [0 35 58000]
 [2 39 52000]
 [0 48 79000]
 [1 50 83000]
 [0 37 67000]
 [2 45 55000]]
dummy :      France  Germany  Spain
0        1        0      0
1        0        0      1
2        0        1      0
3        0        0      1
4        0        1      0
5        1        0      0
6        0        0      1
7        1        0      0
8        0        1      0
9        1        0      0
10       0        0      1
    France  Germany  Spain  Age  Salary
0        1        0      0   44   72000
1        0        0      1   27   48000
2        0        1      0   30   54000
3        0        0      1   38   61000
4        0        1      0   40   68000
5        1        0      0   35   58000
6        0        0      1   39   52000
7        1        0      0   48   79000
8        0        1      0   50   83000
9        1        0      0   37   67000
10       0        0      1   45   55000
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]